server.port=8002
eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka
eureka.instance.prefer-ip-address=true

config.baseurl.endpoint.msvc-products=http://msvc-products:8001

configuration.texto=Configurando entorno Docker
configuration.port=8002
configuration.autor.nombre=Nilton Gonzano
configuration.autor.email=niilton@gmail.com

management.tracing.export.zipkin.endpoint=http://zipkin:9411/api/v2/spans
management.tracing.sampling.probability=1.0
